/* This file is autogenerated. DO NOT CHANGE. All changes will be lost */

#pragma once

#include <QObject>
#include <QMetaType>
#include <QList>
#include <QProtobufObject>
#include <QProtobufLazyMessagePointer>
#include <QSharedPointer>

#include <memory>
#include <unordered_map>

#include <QtQml/QQmlListProperty>
#include <QQmlListPropertyConstructor>

#include <QByteArray>
#include <QDateTime>
#include <QString>

namespace google {
namespace protobuf {
class Timestamp;
using TimestampRepeated = QList<QSharedPointer<Timestamp>>;

}
}


namespace google {
namespace protobuf {
namespace Timestamp_QtProtobufNested {
}

class Timestamp : public QObject
{
    Q_OBJECT
    Q_PROTOBUF_OBJECT
    Q_DECLARE_PROTOBUF_SERIALIZERS(Timestamp)
    Q_PROPERTY(QtProtobuf::int64 seconds READ seconds WRITE setSeconds NOTIFY secondsChanged SCRIPTABLE false)
    Q_PROPERTY(QtProtobuf::int32 nanos_p READ nanos WRITE setNanos NOTIFY nanosChanged SCRIPTABLE false)
    Q_PROPERTY(int nanos READ nanos_p WRITE setNanos_p NOTIFY nanosChanged SCRIPTABLE true)

public:
    Timestamp(QObject *parent = nullptr);
    Timestamp(QtProtobuf::int64 seconds,QObject *parent = nullptr);
    Timestamp(QtProtobuf::int64 seconds,QtProtobuf::int32 nanos,QObject *parent = nullptr);
    Timestamp(const QDateTime &datetime, QObject *parent = nullptr);
    operator QDateTime() const;
    virtual ~Timestamp();
    Timestamp(const Timestamp &other);
    Timestamp &operator =(const Timestamp &other);
    Timestamp(Timestamp &&other);
    Timestamp &operator =(Timestamp &&other);
    bool operator ==(const Timestamp &other) const;
    bool operator !=(const Timestamp &other) const;

    const QtProtobuf::int64 seconds() const {
        return m_seconds;
    }


    const QtProtobuf::int32 nanos() const {
        return m_nanos;
    }

    void setSeconds(const QtProtobuf::int64 &seconds) {
        if (m_seconds != seconds) {
            m_seconds = seconds;
            secondsChanged();
        }
    }

    void setNanos(const QtProtobuf::int32 &nanos) {
        if (m_nanos != nanos) {
            m_nanos = nanos;
            nanosChanged();
        }
    }

    static void registerTypes();

signals:
    void secondsChanged();
    void nanosChanged();

private:
    int nanos_p() const {
        return m_nanos;
    }

    void setNanos_p(const int &nanos) {
        if (m_nanos != nanos) {
            m_nanos = nanos;
            nanosChanged();
        }
    }


private:
    QtProtobuf::int64 m_seconds;
    QtProtobuf::int32 m_nanos;
};

using TimestampRepeated = QList<QSharedPointer<Timestamp>>;

}
}

Q_DECLARE_METATYPE(google::protobuf::Timestamp)
Q_DECLARE_METATYPE(google::protobuf::TimestampRepeated)
Q_DECLARE_METATYPE(QQmlListProperty<google::protobuf::Timestamp>)
